/*
 * MyFrame.java
 *
 * Created on 6 janvier 2009, 09:51
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author  maxime
 */
public class MyFrame extends javax.swing.JFrame {

    /** Creates new form MyFrame */
    public MyFrame() {
	initComponents();
	this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_prin = new javax.swing.JPanel();
        jmb = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmi_quit = new javax.swing.JMenuItem();
        jm_about = new javax.swing.JMenu();
        jmi_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_prin.setMaximumSize(new java.awt.Dimension(800, 600));
        jp_prin.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jp_prinLayout = new javax.swing.GroupLayout(jp_prin);
        jp_prin.setLayout(jp_prinLayout);
        jp_prinLayout.setHorizontalGroup(
            jp_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jp_prinLayout.setVerticalGroup(
            jp_prinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jm_file.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Import ...");
        jm_file.add(jMenuItem1);

        jmi_quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jmi_quit.setText("Quit");
        jmi_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_quitActionPerformed(evt);
            }
        });
        jm_file.add(jmi_quit);

        jmb.add(jm_file);

        jm_about.setText("?");

        jmi_about.setText("About ...");
        jmi_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_aboutActionPerformed(evt);
            }
        });
        jm_about.add(jmi_about);

        jmb.add(jm_about);

        setJMenuBar(jmb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jmi_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_quitActionPerformed
    this.dispose();
}//GEN-LAST:event_jmi_quitActionPerformed

private void jmi_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_aboutActionPerformed
    JOptionPane.showMessageDialog(this, "Projet : Fouille de Données\n" +
	    "Par : \n" +
	    "	Florian COLLIGNON\n" +
	    "	Simon HASNE\n" +
	    "	Maxime HOEFFEL\n" +
	    "	Arnaud KNOBLOCH\n" +
	    "	Romain LAFOND\n" +
	    "	Eric NGUYEN VAN", 
	    "About : Miage SID 2009", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jmi_aboutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jm_about;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenuBar jmb;
    private javax.swing.JMenuItem jmi_about;
    private javax.swing.JMenuItem jmi_quit;
    private javax.swing.JPanel jp_prin;
    // End of variables declaration//GEN-END:variables

}
