
package gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author  maxime
 */
public class MyFrame extends javax.swing.JFrame {

    /** liste des lignes à tracer */
    private static ArrayList<Line2D> lineList = new ArrayList<Line2D>();

    /** Creates new form MyFrame */
    public MyFrame() {
	initComponents();
	this.setVisible(true);
    }

    public static ArrayList<Line2D> getLineList() {
        return lineList;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmb = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmi_quit = new javax.swing.JMenuItem();
        jm_about = new javax.swing.JMenu();
        jmi_about = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jm_file.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Import ...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_file.add(jMenuItem1);

        jmi_quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jmi_quit.setText("Quit");
        jmi_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_quitActionPerformed(evt);
            }
        });
        jm_file.add(jmi_quit);

        jmb.add(jm_file);

        jm_about.setText("?");

        jmi_about.setText("About ...");
        jmi_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_aboutActionPerformed(evt);
            }
        });
        jm_about.add(jmi_about);

        jmb.add(jm_about);

        jMenu1.setText("Menu");
        jmb.add(jMenu1);

        setJMenuBar(jmb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jmi_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_quitActionPerformed
    this.dispose();
}//GEN-LAST:event_jmi_quitActionPerformed

private void jmi_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_aboutActionPerformed
    JOptionPane.showMessageDialog(this, "Projet : Fouille de Données\n" +
	    "Par : \n" +
	    "	Florian COLLIGNON\n" +
	    "	Simon HASNE\n" +
	    "	Maxime HOEFFEL\n" +
	    "	Arnaud KNOBLOCH\n" +
	    "	Romain LAFOND\n" +
	    "	Eric NGUYEN VAN", 
	    "About : Miage SID 2009", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jmi_aboutActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

    
    /* surcharge */
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2 = (Graphics2D)g;
        /* affiche tous les traits */
        for (Line2D line : this.lineList) {
            g2.draw(line);
        }        
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jm_about;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenuBar jmb;
    private javax.swing.JMenuItem jmi_about;
    private javax.swing.JMenuItem jmi_quit;
    // End of variables declaration//GEN-END:variables

}
