package gui;

import cart.Node;
import cart.Scission;
import java.util.Map.Entry;
import projet_fdd.Main;

/**
 * @author  Romain
 */
public class TreeBox extends javax.swing.JPanel {

    /** sujet de l'affichage */
    private Node node;

    /** Creates new form TreeBox */
    public TreeBox(Node node) {
        this.node = node;
        initComponents();
        if(node.isDevelopped() == true)
               this.jButton1.setText("-");

        /* on affiche la liste des scissions possibles */
        System.out.println("Listes:");
        for(Entry e : node.getChartDegrees().entrySet()){
            //System.out.println("Scission : " + ((Scission)e.getKey()).getStringForComboBox() + " [" + (Double)e.getValue() + "]");
            criteresDiscrCB.addItem(new ScissionItem((Scission)e.getKey(), (Double)e.getValue()));
        }
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        criteresDiscrCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder())));

        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jProgressBar1.setForeground(new java.awt.Color(204, 204, 255));
        jProgressBar1.setToolTipText("Répartition de la valeur cible");
        jProgressBar1.setValue(25);
        jProgressBar1.setName(""); // NOI18N
        jProgressBar1.setString("25 occurences");
        jProgressBar1.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("CANCER : \"NON\"");

        criteresDiscrCB.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        criteresDiscrCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteresDiscrCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Critères discriminants");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criteresDiscrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteresDiscrCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {criteresDiscrCB, jButton1});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jButton1.getText().equals("-")){
           node.setDevelopped(false);
           /* réaffiche l'arbre */
           Main.drawRootNode();
       }else{
        // retourne le parametre de scission de ce noeud !
        Main.clickOnTreeBox(node, ((ScissionItem)criteresDiscrCB.getSelectedItem()).getScission());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void criteresDiscrCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteresDiscrCBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_criteresDiscrCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox criteresDiscrCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
