// file: VentecdOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package protege;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: VentecdOntology.java
 * @author ontology bean generator
 * @version 2008/11/4, 10:58:26
 */
public class VentecdOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "ventecd";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new VentecdOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String VENDRECD_CD="cd";
    public static final String VENDRECD="VendreCD";
    public static final String CD_INPROMOTION="inPromotion";
    public static final String CD_NBTRACK="nbTrack";
    public static final String CD_PRICE="price";
    public static final String CD_TITLE="title";
    public static final String CD="CD";

  /**
   * Constructor
  */
  private VentecdOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema cdSchema = new ConceptSchema(CD);
    add(cdSchema, protege.CD.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema vendreCDSchema = new PredicateSchema(VENDRECD);
    add(vendreCDSchema, protege.VendreCD.class);


    // adding fields
    cdSchema.add(CD_TITLE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    cdSchema.add(CD_PRICE, (TermSchema)getSchema(BasicOntology.FLOAT), 0, ObjectSchema.UNLIMITED);
    cdSchema.add(CD_NBTRACK, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.OPTIONAL);
    cdSchema.add(CD_INPROMOTION, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.OPTIONAL);
    vendreCDSchema.add(VENDRECD_CD, cdSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
